# Generated by Django 3.2.4 on 2021-06-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='replies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='starter',
            field=models.CharField(default='名無し', max_length=10),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
