# Generated by Django 2.1 on 2021-06-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='starter',
            field=models.CharField(max_length=10),
        ),
    ]
