# Generated by Django 3.2.4 on 2021-06-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmodel',
            name='topic_id',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='message_id',
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='topic_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
