# Generated by Django 3.2.4 on 2021-06-13 02:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0003_auto_20210612_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.PositiveIntegerField()),
                ('user', models.CharField(max_length=10)),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
